import 'package:fuksiarz/models/event_category.dart';

const availableCategories = [
  EventCategory([1], ['Piłka nożna']),
  EventCategory([2], ['Koszykówka']),
  EventCategory([3], ['Baseball']),
  EventCategory([4], ['Hokej na lodzie']),
  EventCategory([5], ['Tenis']),
  EventCategory([6], ['Piłka ręczna']),
  EventCategory([7], ['Unihokej']),
  EventCategory([10], ['Siatkówka']),
  EventCategory([12], ['Rugby']),
  EventCategory([13], ['Futbol australijski']),
  EventCategory([16], ['Futbol amerykański']),
  EventCategory([17], ['Kolarstwo']),
  EventCategory([18], ['Zakłady specjalne']),
  EventCategory([20], ['Tenis stołowy']),
  EventCategory([21], ['Krykiet']),
  EventCategory([22], ['Darts']),
  EventCategory([23], ['F1']),
  EventCategory([24], ['Hokej na trawie']),
  EventCategory([26], ['Piłka wodna']),
  EventCategory([29], ['Futsal']),
  EventCategory([31], ['Badminton']),
  EventCategory([34], ['Siatkówka plażowa']),
  EventCategory([40], ['Boks']),
  EventCategory([41], ['MMA']),
  EventCategory([52], ['CASHBACK']),
  EventCategory([70], ['Counter Strike']),
  EventCategory([72], ['Dota']),
  EventCategory([155146], ['Motocykle']),
];
